config/routes.rb
Rails.application.routes.draw do
  resources :buckets
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  #  root "tasks#index"
   root "buckets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bucket.rb
class Bucket < ApplicationRecord
    has_many :tasks, :dependent => :destroy                             # enables the connection of tasks and buckets and ensure that the buckets can be deleted even when there is a task inside
    validates :name, presence: true                                     # ensures that all bucket have names

    def self.get_by_status(status)                                      # method to get the current status of the bucket
        self.all.select do |bucket|
            bucket.status == status
        end
    end

    def update_status                                                  # method to check what is the current status of the bucket
        if self.tasks == []
            self.status = "Empty"
        elsif self.tasks.any?{|task| task.status == "Pending"}
            self.status = "Pending"
        else
            self.status = "Completed"
        end
        self.save
    end

    def tasks_by_status(status)                                        # method to acquire the status of the tasks
        self.tasks.select do |task|
            task.status == status
        end
    end

end

app/models/priority.rb
class Priority < ApplicationRecord
   has_many :tasks                  # enables the connection of priorities database to tasks database
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :bucket                                  # maintain the primary key-foreign key relationship wih bucket
  has_one :priority, foreign_key: :priority_id        # connected to priority which has a foreign key (id)
  validates :name, presence: true                     # ensures that all tasks have names

  def self.get_by_status(status)                      # checking the current status of the tasks
    self.all.select do |task|
        task.status == status
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
    def index                                                        # method to help with the status of the buckets
        @empty_buckets = Bucket.get_by_status("Empty")
        @pending_buckets = Bucket.get_by_status("Pending")
        @completed_buckets = Bucket.get_by_status("Completed")
    end

    def new                                                          # method for initiating new bucket
        @bucket = Bucket.new
    end

    def create                                                       # method for creating the bucket
        @bucket = Bucket.create(bucket_params(:name, :description))  # creates bucket from user's name and description
        @bucket.status = "Empty"                                     # initiating the bucket's status as empty
        @bucket.save                                                 # saving the bucket in the database
        redirect_to bucket_path(@bucket)                             # after the creation of the bucket, the user will be redirected to the next path
    rescue ActionController::UrlGenerationError                      # Exception Handling if the next path's creation failed
        render :file => "#{Rails.root}/public/alert.html"
    end

    def show                                                         # method for showing all records of buckets
        @bucket = Bucket.find(params[:id])                           
    rescue ActiveRecord::RecordNotFound                              # Exception Handling
        redirect_to root_path                                        # if the bucket's id is deleted or no longer available, this will redirect the user to the root path
    end

    def edit                                                         # method for editing a bucket
        @bucket = Bucket.find(params[:id])
    end

    def update                                                       # method for updating bucket's contents
        @bucket = Bucket.find(params[:id])
        @bucket.update(bucket_params(:name, :description))           
        @bucket.update_status
        redirect_to bucket_path(@bucket)
    end

    def destroy                                                      # method for deleting bucket
        @bucket = Bucket.find(params[:id])
        @bucket.destroy
        redirect_to bucket_path
    end

    private                                                          # method for defining which parameter is required and which objects is permitted to be updated
    def bucket_params(*args)
        params.require(:bucket).permit(*args)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index                                                        # method to help with the status of the tasks
        @pending_tasks = Task.get_by_status("Pending")
        @completed_tasks = Task.get_by_status("Completed")
    end

    def new                                                          # method for initiating new task
        @task = Task.new
    end

    def create                                                       # method for creating the bucket
        @task = Task.create(task_params(:name, :description, :bucket_id, :priority_id)) 
        @task.status = "Pending"
        @task.save
        @task.bucket.update_status
        redirect_to task_path(@task)
    rescue NoMethodError                                            # Exception Handling if bucket or task is failed to be recognized
        render :file => "#{Rails.root}/public/alert.html"
    rescue ActionController::UrlGenerationError                     # Exception Handling if the next path's creation failed
        render :file => "#{Rails.root}/public/alert.html"
    end

    def show                                                        # method for showing all records of tasks
        @task = Task.find(params[:id])
    end

    def edit                                                        # method to initiate editing of the tasks
        @task = Task.find(params[:id])
    end

    def update                                                      # method for updating the content of the tasks
        @task = Task.find(params[:id])
        @task.update(task_params(:name, :description, :status, :bucket_id, :priority_id))
        @bucket = @task.bucket.update_status
        redirect_to task_path(@task)
    end

    def destroy                                                     # method for deleting tasks
        @task = Task.find(params[:id]).destroy
        redirect_to tasks_path
    end

    private                                                         # method for defining which parameter is required and which objects is permitted to be updated
    def task_params(*args)
        params.require(:task).permit(*args)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/buckets/_footer.html.erb
<div class="footer">
    <ul class="nav justify-content-center">
        <div class="credits">
          <li class="nav-item">Aceres</li>
        </div>

        <div class="credits">
          <li class="nav-item">Arellano</li>
        </div>

        <div class="credits">
          <li class="nav-item">Bechayda</li>
        </div>

        <div class="credits">
          <li class="nav-item">De Vera</li>
        </div>

        <div class="credits">
          <li class="nav-item">Encarnacion</li>
        </div>

        <div class="credits">
          <li class="nav-item">Malinay</li>
        </div>
    </ul>

    <div class="credits">
      © 2022 TEAM F
    </div>
</div>

app/views/buckets/_header.html.erb
<div class="header">
  <div class="title">
    Task Management System
  </div>  

 <div class="all">  
      <%=link_to "All Buckets", buckets_path, class:"buckets"%>
      <%=link_to "All Tasks", tasks_path, class:"tasks"%>
 </div>
</div>

app/views/buckets/edit.html.erb
<br>
<div class = "subtitle d-flex justify-content-start">
    <%= "EDIT: " + @bucket.name %>
</div>
<br>
<div class="form d-flex justify-content-start">
    <%= form_for(@bucket) do |f| %>
        <%= f.label :name, class: "label"%><br>
        <%= f.text_field :name, class: "textField", maxlength: 50%><br>
        <%= f.label :description,  class: "label"%><br>
        <%= f.text_area :description, class: "textArea"%><br>
        <%= f.submit 'Update Bucket', class: "submitButton btn-primary"%><br>
    <% end %>
    <%= button_to "Delete Bucket", @bucket, :method => :delete, class: "deleteButton btn-primary" %><br>
    <%= link_to "Cancel", buckets_path, class: "cancelButton btn-primary" %><br>
</div>

app/views/buckets/index.html.erb
<br>
<div class="d-flex align-items-center justify-content-center">
    <h1>BUCKETS LIST</h1>
</div>
<br>

<div class="d-flex align-items-center justify-content-center">
    <%= button_to "Create Bucket", new_bucket_path, class:"createBtn btn-primary", method: :get %>
</div>
<br> <br>

<div class="container text-center">
  <div class="row align-items-center justify-content-center">
    <div class="col-4">
      <p class= "showLabel">Empty Buckets</p>
    </div>
    <div class="col-4">
      <p class= "showLabel">Pending Buckets</p>
    </div>
    <div class="col-4">
      <p class= "showLabel">Completed Buckets</p>
    </div>
  </div>

  <div class="row align-self-start justify-content-center">
    <div class="col-4">
        <% @empty_buckets.each do |bucket| %>
        <p class= "bucketList"><span style="font-weight:normal"><%= link_to bucket.name, bucket_path(bucket), class: "link-dark" %></span></p>
        <% end %>
    </div>


    <div class="col-4">
        <% @pending_buckets.each do |bucket| %>
        <p class= "bucketList"><span style="font-weight:normal"><%= link_to bucket.name, bucket_path(bucket), class: "link-dark" %></span></p>
        <% end %>
    </div>

    
    <div class="col-4">
        <% @completed_buckets.each do |bucket| %>
        <p class= "bucketList"><span style="font-weight:normal"><%= link_to bucket.name, bucket_path(bucket), class: "link-dark" %></span></p>
        <% end %>
    </div>
  </div>
</div>

app/views/buckets/new.html.erb
<br>
<div class = "subtitle d-flex justify-content-start">
    Create New Bucket
</div>
<br>
<div class="form d-flex justify-content-start">
    <%= form_for(@bucket) do |f| %>
        <%= f.label :name, class: "label"%><br>
        <%= f.text_field :name, class: "textField", maxlength: 50%><br>
        <%= f.label :description,  class: "label"%><br>
        <%= f.text_area :description, class: "textArea"%><br>
        <%= f.submit "Create Bucket", class: "submitButton  btn-primary"%><br>
    <% end %>
    <%= link_to "Cancel", buckets_path, class: "cancelButton  btn-primary" %><br>
</div>

app/views/buckets/show.html.erb
<br>
<%= link_to "Back", buckets_path, class: "Back btn-primary" %>
<br>

<div class = "taskName d-flex justify-content-center">
    <%= @bucket.name %>
</div><br>

<p class ="desLabel"> Description: </p>
<p class = "description"><%= @bucket.description %></p><br><br>

<div class="container text-center">
    <div class="row align-items-center justify-content-center">
        <div class="col-4">
            <p class="showLabel">Pending Tasks</p>
        </div>
        <div class="col-4">
            <p class="showLabel">Completed Tasks</p>
        </div>
    </div>


<div class="row align-self-start justify-content-center">
    <div class="col-4">
        <% @bucket.tasks_by_status("Pending").each do |task| %>
        <p class= "content" style="font-weight:normal"><%= link_to task.name, task_path(task) %></p>
        <% end %>
    </div>

    <div class="col-4">
        <% @bucket.tasks_by_status("Completed").each do |task| %>
        <p class= "content" style="font-weight:normal"><%= link_to task.name, task_path(task) %></p>
        <% end %>
    </div>
<div>
<br><br>



<div class="d-flex align-items-center justify-content-center">
    <div class = "col-2">
        <%= button_to "Edit Bucket", edit_bucket_path(@bucket), class:"button btn-primary", method: :get %>
    </div>
    <div class = "col-2">
        <%= button_to "+ Add Task", new_task_path, class: "button btn-primary", method: :get %></span>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task Management System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>

  </head>


  <body class= body>

    <%= render 'buckets/header' %>

    <%= yield %>

    <%= render 'buckets/footer' %>
  </body>

</html>

app/views/tasks/edit.html.erb
<div class = "subtitle d-flex justify-content-start">
    <br><h1><%= "Edit " + @task.name %></h1>
</div>
<br>

 <div class="form d-flex justify-content-start">
  <div class="d-flex flex-row">
    <%= form_for(@task) do |f| %>
      <%= f.label :name, class: "content"%><br>
      <%= f.text_field :name, class: "textField", maxlength: 50%><br>
      <%= f.label :description, class: "content" %><br>
      <%= f.text_area :description, class: "textArea" %>
    </div>
    <div class = "d-flex flex-row">
        <div><%= f.label "Bucket", class: "rightLabel" %></div><br>
        <div><br><%= f.collection_select :bucket_id, Bucket.order(:name),:id, :name, {}, {class: "bucketField"} %></div>
        <div><%= f.label "Priority", class: "priorityLabel" %></div>
        <div><%= f.collection_select :priority_id, Priority.order(:name),:id, :name, {}, {class: "priorityField"}%><br></div>
        <div class= "checkLabel"><%= f.check_box :status, {}, "Completed", "Pending" %>  Done<br></div>
    </div>
</div>

<div class="d-flex flex-row justify-content-align-center">
      <div>
        <%= f.submit 'Finish', :class => "createTaskButton" %>
        <% end %>
      </div>
      <div>
        <%= button_to "Delete Task", @task, :method => :delete, data: {confim: 'Are you sure?'}, :class => "deleteTaskButton" %>
      </div>
      <div>
        <%=link_to "Cancel", tasks_path, class: "cancelCreateButton" %></div>
    </div>
  </div>
    

app/views/tasks/index.html.erb
<br>
<div class="d-flex align-items-center justify-content-center">
    <h1>TASK LIST</h1>
</div>
<br>

<div class ="container text-center">
 <div class="row align-items-center justify-content-center">
  <div class="col-4">
        <p class= "showLabel">Create Tasks</p>
  </div>
    <div class="col-4">
        <p class= "showLabel">Pending Tasks</p>
   </div>
  <div class="col-4">
        <p class= "showLabel">Completed Tasks</p>
  </div>
 </div>
<div class="row align-self-start justify-content-center">
  <div class="col-4">
        <p><span style="font-weight:normal">
        <%= button_to "+ New", new_task_path, class: "newBtn btn-primary", method: :get %></span></p>
  </div>
    <div type = "button" class="col-4">
        <% @pending_tasks.each do |task| %>
        <p class= "taskList"><span style="font-weight:normal"><%= link_to task.name, task_path(task), class: "link-dark" %><br>
         <button class="btn btn-outline-primary btn-xs" disabled> <%= task.bucket.name %> </button>

        
          <%# <% Task.all.each do |priority_id| %> 
          <%# <% end %> 
              <% if task.priority_id == 1 %>
                    <button class="btn btn-danger btn-xs m-2" disabled>
                        <%= "Urgent" %> 
                    </button>
                <% elsif task.priority_id == 2 %> 
                      <button class="btn btn-warning btn-xs m-2" disabled>
                        <%= "High" %> 
                    </button>
                 <% elsif task.priority_id == 3 %>
                      <button class="btn btn-primary btn-xs m-2" disabled>
                        <%= "Normal" %> 
                    </button>

                <% elsif task.priority_id == 4 %>
                        <button class="btn btn-secondary btn-xs m-2" disabled>
                        <%= "Low" %> 
                    </button>
                <% else %>
                      <%= "No Priority" %> 
                <% end %>
        
        </span></p>
        <% end %>
   </div>
  <div class="col-4">
        <% @completed_tasks.each do |task| %>
        <p class= "taskList"><span style="font-weight:normal"><%= link_to task.name, task_path(task), class: "link-dark" %> <br>
        <button class="btn btn-outline-primary btn-xs m-2" disabled> <%= task.bucket.name %> </button></span></p>
        <% end %>
  </div>
 </div>
</div>

app/views/tasks/new.html.erb
<div class = "subtitle d-flex justify-content-start">
    <br><h1>CREATE NEW TASK</h1>
</div>
<br>

 <div class="form d-flex justify-content-start">
  <div class="d-flex flex-row">
    <%= form_for(@task) do |f| %>
      <%= f.label :name, class: "content"%><br>
      <%= f.text_field :name, class: "textField", maxlength: 50%><br>
      <%= f.label :description, class: "content" %><br>
      <%= f.text_area :description, class: "textArea" %><br>
    </div>
    <div class = "d-flex flex-row">
        <div><%= f.label "Bucket", class: "rightLabel" %></div>
        <div><br><%= f.collection_select :bucket_id, Bucket.order(:name),:id, :name, {}, {class: "bucketField"} %></div>
        <div><%= f.label "Priority", class: "priorityLabel" %></div>
        <div><%= f.collection_select :priority_id, Priority.order(:name),:id, :name, {}, {class: "priorityField"}%><br></div>
    </div>
</div>

<div class="d-flex flex-row justify-content-align-center">
      <div>
        <%= f.submit 'Create Task', :class => "createTaskButton" %>
        <% end %>
      </div>
      <div>
        <%=link_to "Cancel", tasks_path, class: "deleteTaskButton" %></div>
    </div>
  </div>

app/views/tasks/show.html.erb
<br>
<%= link_to "Back", tasks_path, class: "Back btn-primary" %>
<br>

<div class = "taskName d-flex align-items-center justify-content-center">
    <%= @task.name %>
</div> <br>

<p class ="desLabel">Desciption: </p>
<p class = "description"> <%= @task.description %></p><br><br>


<div class="container text-center">
    <div class="row align-items-center justify-content-center">
        <div class="col-4">
            <p class="showLabel">Bucket: </p>
         </div>

         <div class="col-4">
            <p class="showLabel">Priority:</p>
        </div>

         <div class="col-4">
            <p class="showLabel">Status:</p>
        </div>
    </div>
</div>

<div class="container text-center">
    <div class="row align-self-start justify-content-center">
        <div class="col-4">
            <p class = "content"> <%= @task.bucket.name %> </p>
        </div>

        <div class="col-4">
        <p class="content">
            <% if @task.priority_id == 1 %>
                        <%= "Urgent" %>
                <% elsif @task.priority_id == 2 %> 
                        <%= "High" %> 
                 <% elsif @task.priority_id == 3 %>
                        <%= "Normal" %> 
                <% elsif @task.priority_id == 4 %>
                        <%= "Low" %> 
                <% else %>
                      <%= "No Priority" %> 
                <% end %>
        </p>
        </div>

        <div class="col-4">
            <p class = "content"> <%= @task.status %>  </p>
        </div>
    </div>
</div>

<br><br>

<div class = "d-flex align-items-center justify-content-center">
    <%= button_to "Edit Task",  edit_task_path(@task), class: "button btn-primary", method: :get %>
</div>